# Generated by Django 4.2.19 on 2025-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_bus_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='icon',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_icon',
            field=models.ImageField(blank=True, default=None, help_text='Upload an icon/image for this bus', null=True, upload_to='bus_icons/'),
        ),
    ]
