# Generated by Django 4.2.19 on 2025-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_remove_bus_icon_bus_bus_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='from_address',
            field=models.CharField(blank=True, help_text='Starting location address of the bus route', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='from_lat',
            field=models.FloatField(blank=True, help_text='Latitude of the starting location', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='from_lng',
            field=models.FloatField(blank=True, help_text='Longitude of the starting location', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='to_address',
            field=models.CharField(blank=True, help_text='Destination address of the bus route', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='to_lat',
            field=models.FloatField(blank=True, help_text='Latitude of the destination location', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='to_lng',
            field=models.FloatField(blank=True, help_text='Longitude of the destination location', null=True),
        ),
    ]
